# Generated by Django 5.0.3 on 2024-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('subjects', models.TextField()),
                ('bookshelves', models.TextField()),
                ('download_links', models.JSONField()),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
