# Generated by Django 5.0.3 on 2024-03-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appbook_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
